[package]
name = "me_guinea_pig"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "me_guinea_pig"
path = "src/main.rs"

[dependencies]
bevy = { version = "=0.19.0", features = ["android-native-activity"] }
bevy_render = { version = "0.19.0", features = ["gles"] }
winit = "0.30"

[patch.crates-io]
winit = { git = "https://github.com/rust-windowing/winit.git", rev = "c28e425214e82bdb86dcdf89c9488554a18e24b2" }
bevy_android = { git = "https://github.com/Johannes0021/bevy.git", rev = "a244a51175bee80b21ef0416650662cfc0b7896b" }

[package.metadata.android]
app_name = "Me, Guinea Pig"
package_name = "com.meguineapig.app"
assets = "assets"
resource = "android/app/src/main/res"
icon = "android/app/src/main/res/mipmap/ic_launcher.png"

[package.metadata.commands]
android = "bash scripts/run-android.sh"
